### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by AzHicham** [comment]
Sorry I need to fix some CI workflows in order to let people outside of this repo create PR that pass CI

**Comment by jayvdb** [comment]
I don't mind if you merge when the checks are failing here - they will be green when the CI runs on `main`.

btw I had a look into the Makefile , and came across https://github.com/EmbarkStudios/gsutil which has slightly different syntax but does the same job as the very outdated PyPI equivalent which uses a bunch of unmaintained dependencies.  Might be worth using.

**Comment by AzHicham** [comment]
> I don't mind if you merge when the checks are failing here - they will be green when the CI runs on `main`.
> 
> btw I had a look into the Makefile , and came across https://github.com/EmbarkStudios/gsutil which has slightly different syntax but does the same job as the very outdated PyPI equivalent which uses a bunch of unmaintained dependencies. Might be worth using.

I'll give it a try, asap.

**Pull request merged**
